// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYI0x0aZAFcxsnKQ86YjBl0rfoiUFNZrA',
    appId: '1:279101753310:web:f2fcaa9529aac1dad83f4f',
    messagingSenderId: '279101753310',
    projectId: 'elnagm39-5b7a9',
    authDomain: 'elnagm39-5b7a9.firebaseapp.com',
    storageBucket: 'elnagm39-5b7a9.appspot.com',
    measurementId: 'G-XVJGW136ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYjox8MvmpWl5-ncllWH4WAaTYpzVjuCo',
    appId: '1:279101753310:android:3d0dfd76cb56da5dd83f4f',
    messagingSenderId: '279101753310',
    projectId: 'elnagm39-5b7a9',
    storageBucket: 'elnagm39-5b7a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALbn2gj3f1m0MJByA49zTQseu3ivoWyGo',
    appId: '1:279101753310:ios:e911ae54f53a12bcd83f4f',
    messagingSenderId: '279101753310',
    projectId: 'elnagm39-5b7a9',
    storageBucket: 'elnagm39-5b7a9.appspot.com',
    iosClientId: '279101753310-069116msiah1pgjb6ou9bqa8i559biia.apps.googleusercontent.com',
    iosBundleId: 'com.ui.reflective',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALbn2gj3f1m0MJByA49zTQseu3ivoWyGo',
    appId: '1:279101753310:ios:43c1ec1afdbae009d83f4f',
    messagingSenderId: '279101753310',
    projectId: 'elnagm39-5b7a9',
    storageBucket: 'elnagm39-5b7a9.appspot.com',
    iosClientId: '279101753310-5rfk5gkgfuau1ke2ddtqtim639sqimaj.apps.googleusercontent.com',
    iosBundleId: 'com.ui.reflective.RunnerTests',
  );
}
